### ISSUE TITLE
The following plugins slow down the start of Glyphs.

### ISSUE THREAD

**Issue by samgobin** [mekkablue/ShowGlyphsInLabelColor#3]
Gives a prompt: The following plugins slow down the start of Glyphs. Please update them, or contact the developer to improve performance. GlyphsInLabelColor.OLD.glyphsReporter. I have updateed and cannot find he old version in preferences. How can I fix this?

**Comment by mekkablue** [comment]
Please delete the .glyphsReporter file from your Plugins folder, and reinstall via the plug-in manager. Then restart the app.

**Comment by samgobin** [comment]
Where can I find the plugins folder?

Op 12 jul. 2019, om 13:16 heeft Rainer Erich Scheichelbauer <notifications@github.com> het volgende geschreven:

Please delete the .glyphsReporter file from your Plugins folder, and reinstall via the plug-in manager. Then restart the app.

**Comment by samgobin** [comment]
sorry, found it (I was in the wrong library file…)

Op 12 jul. 2019, om 13:31 heeft sgobin <sgobin@online.nl> het volgende geschreven:

Where can I find the plugins folder?

Op 12 jul. 2019, om 13:16 heeft Rainer Erich Scheichelbauer <notifications@github.com <mailto:notifications@github.com>> het volgende geschreven:

Please delete the .glyphsReporter file from your Plugins folder, and reinstall via the plug-in manager. Then restart the app.

**Comment by samgobin** [comment]
It doesn’t help. Now it is going down the list of plugins. Any suggestions?


Op 12 jul. 2019, om 13:35 heeft sgobin <sgobin@online.nl> het volgende geschreven:

sorry, found it (I was in the wrong library file…)

Op 12 jul. 2019, om 13:31 heeft sgobin <sgobin@online.nl <mailto:sgobin@online.nl>> het volgende geschreven:

Where can I find the plugins folder?

Op 12 jul. 2019, om 13:16 heeft Rainer Erich Scheichelbauer <notifications@github.com <mailto:notifications@github.com>> het volgende geschreven:

Please delete the .glyphsReporter file from your Plugins folder, and reinstall via the plug-in manager. Then restart the app.

**Comment by mekkablue** [comment]
The warning comes when a plug-in initialization takes too long. 

> Now it is going down the list of plugins

So this issue is not related to this particular plug-in. I will close this thread then. A better place to discuss this is forum.glyphsapp.com

**Comment by samgobin** [comment]
thnx

Op 16 jul. 2019, om 16:42 heeft Rainer Erich Scheichelbauer <notifications@github.com> het volgende geschreven:

The warning comes when a plug-in initialization takes too long.

Now it is going down the list of plugins

So this issue is not related to this particular plug-in. I will close this thread then. A better place to discuss this is forum.glyphsapp.com
